apiVersion: v1
kind: Service
metadata:
  name: devops
  lables:
    app: devops
spec:
  selector:
    app: devops
  ports:
    - port: 8080
      targetPort: 80
      nodePort: 31200
  type: LoadBalancer
